2022-04-20 15:49:55,159 INFO    MainThread:131620 [wandb_setup.py:_flush():75] Loading settings from /home/ubuntu/.config/wandb/settings
2022-04-20 15:49:55,159 INFO    MainThread:131620 [wandb_setup.py:_flush():75] Loading settings from /home/ubuntu/environment/tutorial/wandb/settings
2022-04-20 15:49:55,159 INFO    MainThread:131620 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-20 15:49:55,159 INFO    MainThread:131620 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'tutorial2.py', 'program': 'tutorial2.py'}
2022-04-20 15:49:55,159 INFO    MainThread:131620 [wandb_init.py:_log_setup():438] Logging user logs to /home/ubuntu/environment/tutorial/wandb/run-20220420_154955-1lpn2pqq/logs/debug.log
2022-04-20 15:49:55,159 INFO    MainThread:131620 [wandb_init.py:_log_setup():439] Logging internal logs to /home/ubuntu/environment/tutorial/wandb/run-20220420_154955-1lpn2pqq/logs/debug-internal.log
2022-04-20 15:49:55,159 INFO    MainThread:131620 [wandb_init.py:init():472] calling init triggers
2022-04-20 15:49:55,159 INFO    MainThread:131620 [wandb_init.py:init():475] wandb.init called with sweep_config: {}
config: {}
2022-04-20 15:49:55,160 INFO    MainThread:131620 [wandb_init.py:init():525] starting backend
2022-04-20 15:49:55,160 INFO    MainThread:131620 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-04-20 15:49:55,170 INFO    MainThread:131620 [backend.py:ensure_launched():219] starting backend process...
2022-04-20 15:49:55,173 INFO    MainThread:131620 [backend.py:ensure_launched():224] started backend process with pid: 131629
2022-04-20 15:49:55,174 INFO    MainThread:131620 [wandb_init.py:init():534] backend started and connected
2022-04-20 15:49:55,179 INFO    MainThread:131620 [wandb_init.py:init():598] updated telemetry
2022-04-20 15:49:55,189 INFO    MainThread:131620 [wandb_init.py:init():629] communicating run to backend with 30 second timeout
2022-04-20 15:50:24,087 WARNING MainThread:131620 [wandb_init.py:init():1017] interrupted
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 996, in init
    run = wi.init()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 630, in init
    run_result = backend.interface.communicate_run(run, timeout=30)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 210, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 323, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 225, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
